disabled = false
languageCode = "ru"
languageName = "Русски"
weight = 1
title = "Рафаэль Маматходжаев"

[params]
  displayName = "Рафаэль Маматходжаев"
  description = "Frontend / Fullstack разработчик • Санкт-Петербург"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
    name = "Маматходжаев Рафаэль"
    headline = "Frontend / Fullstack"
    bio = "Студент ИТМО. Коммерческий опыт: Яндекс Музыка (стаж.), Фора Софт, фриланс-проекты."
    links = [
      { email = "rawoline@gmail.com" },
      { github = "https://github.com/rawline" },
      # добавь свои:
      # { telegram = "https://t.me/..." },
      # { linkedin = "https://www.linkedin.com/in/..." }
    ]
